#!/bin/bash
netid='saf258'

if [ "$1" == 'clean' ]; then
    rm -f saf258.tar
    exit 0
fi

# delete any previous .tar files
rm $netid.tar &> /dev/null

# make a copy of the project with name $netid
cd ..
cp -R chatroom $netid

# remove unnecessary files
cd $netid
rm -rf .git .gitignore process test_output master.py grading.py docs package
find . -iname '*.sw*' | xargs rm -f
cd tests
ls | grep -v '_.*' | xargs rm -f

# tar the project and print the contents
cd ../..
tar -cf $netid.tar $netid && tar -tf $netid.tar

# remove the project copy and move the .tar file to the project folder
rm -rf $netid
mv $netid.tar chatroom
