#!/bin/bash
trap ctrl_c INT
function ctrl_c() {
        killall python
        ./stopall
        exit 1
}

testdir='./tests/grading_tests/'
files=$(python -c "
from os import listdir
from os.path import isfile, join
import os

testdir = '$testdir'
files = map(lambda x: x[:x.find('.input')], [f for f in listdir(testdir)
        if isfile(join(testdir, f)) and f.find('.input') > -1])
print ' '.join(files)")

./build

test_file() {
    file="$1"
    output="$(./master.py < $testdir$file'.input')"
    diff=$(diff -s <(echo "$output") $testdir$file'.output')
    if [ "$?" != 0 ]; then
        echo FAILURE: $file.input
        echo GOT:
        echo "$output" | nl
        echo
        echo WANT:
        cat $testdir$file'.output' | nl
        echo
        echo "$diff"
        exit 1
    fi
    echo PASS: $file.input
}

# run a single test if provided
if [ -n "$1" ]; then
    test_file "$1"
    exit 0
fi

# run all tests
for file in $files; do
    test_file "$file"
done

echo -----------------------
echo SUCCESS: All tests pass
